### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by tugii21** [tugii21/Garnish#1]
As a new user**,  **I want** to have the option to create an account and then log in to the website **so that I can** start using the services and features available to registered users.

**Comment by tugii21** [comment]
- [x] Implement User Registration Form:

- [x]  Implement User Authentication:

- [x]  Create Database Schema:

- [x]  Implement User Interface (UI):

- [x]  Error Handling and Validation:


- [x] Testing and Debugging:

-[] Documentation:
